DATASET_NAME='ILSVRC'
DATA_ROOT='./dataset'
METADATA_ROOT='./metadata'

WSOL_METHOD='vitol'
VIT_TYPE='vit_deit'
pADL_LAYER=True
ATTENTION_GENERATION_METHOD='grad_rollout'

BATCH_SIZE=64
WORKERS=16

CHECKPOINT_NAME='ViTOL-DeiT-B_IMAGENET_last.pth.tar'
SCOREMAP_THRESHOLD=0.208
EXPERIMENT_NAME='eval_deitB_gar_ilsvrc' 
