DATASET_NAME='ILSVRC'
DATA_ROOT='./dataset'
METADATA_ROOT='./metadata'

WSOL_METHOD='vitol'
VIT_TYPE='deit_small'
pADL_LAYER=True
ATTENTION_GENERATION_METHOD='grad_rollout'

BATCH_SIZE=64
WORKERS=16

CHECKPOINT_NAME='ViTOL-DeiT-S_IMAGENET_best.pth.tar'
SCOREMAP_THRESHOLD=0.165
EXPERIMENT_NAME='eval_deitS_gar_ilsvrc' 
